version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: learning_platform
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes  # Enable persistence
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge